#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/safedesk/safedesk /usr/bin/safedesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/safedesk.service ]; then
			rm -f /etc/systemd/system/safedesk.service /usr/lib/systemd/system/safedesk.service /usr/lib/systemd/user/safedesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/safedesk/files/systemd/safedesk.service /usr/lib/systemd/system/safedesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload safedesk.service: Unit safedesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/safedesk.service:10: Executable path is not absolute: pkill -f "safedesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/safedesk.service
		fi
		systemctl daemon-reload
		systemctl enable safedesk
		systemctl start safedesk
	fi
fi
